"""Hogskoleprovet (HP) question model and starter question bank.

This module provides:
- Shared section metadata for all 8 HP sections.
- Passage and diagram registries (LAS/ELF and DTK).
- A starter bank spanning all sections.
- Optional imported question loading from JSON generated by hp_pdf_parser.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

HP_SECTIONS: dict[str, dict[str, Any]] = {
    "xyz": {
        "display": "XYZ",
        "name": "Matematisk problemlosning",
        "domain": "quantitative",
        "choices_count": 4,
    },
    "kva": {
        "display": "KVA",
        "name": "Kvantitativa jamforelser",
        "domain": "quantitative",
        "choices_count": 4,
        "fixed_choices": [
            "A) Kvantitet I ar storre",
            "B) Kvantitet II ar storre",
            "C) Kvantiteterna ar lika stora",
            "D) Informationen ar otillracklig",
        ],
    },
    "nog": {
        "display": "NOG",
        "name": "Kvantitativa resonemang",
        "domain": "quantitative",
        "choices_count": 5,
        "fixed_choices": [
            "A) ej genom de bada pasteendena",
            "B) i (1) och (2) var for sig",
            "C) i (1) tillsammans med (2)",
            "D) i (2) men ej i (1)",
            "E) i (1) men ej i (2)",
        ],
    },
    "dtk": {
        "display": "DTK",
        "name": "Diagram, tabeller och kartor",
        "domain": "quantitative",
        "choices_count": 4,
    },
    "ord": {
        "display": "ORD",
        "name": "Ordforstaelse",
        "domain": "verbal",
        "choices_count": 5,
    },
    "las": {
        "display": "LAS",
        "name": "Lasforstaelse",
        "domain": "verbal",
        "choices_count": 4,
    },
    "mek": {
        "display": "MEK",
        "name": "Meningskomplettering",
        "domain": "verbal",
        "choices_count": 4,
    },
    "elf": {
        "display": "ELF",
        "name": "English Reading Comprehension",
        "domain": "verbal",
        "choices_count": 4,
    },
}

KVA_FIXED_CHOICES = HP_SECTIONS["kva"]["fixed_choices"]
NOG_FIXED_CHOICES = HP_SECTIONS["nog"]["fixed_choices"]

HP_PASSAGES: dict[str, dict[str, Any]] = {
    "hp_starter_las_1": {
        "title": "Urban odling och social tillit",
        "language": "sv",
        "text": (
            "Forskning om urban odling har ofta fokuserat pa skord och klimatnytta. "
            "En nyare forskningslinje betonar i stallet sociala effekter. I en "
            "svensk longitudinal studie foljdes 18 odlingsforeningar under sex ar. "
            "Forskarna fann att medlemmarnas upplevda tillit till grannar okade "
            "signifikant i omraden dar odlingen kombinerades med oppna aktiviteter. "
            "Samtidigt var effekten svag i foreningar med hog intern slutenhet. "
            "Studien visar dock inte att odling i sig orsakar tillit; ett alternativt "
            "tolkningsspar ar att platser med redan starkt foreningsliv lattare "
            "attraherar odlingsinitiativ. Forfattarna foreslar darfor randomiserade "
            "pilotprojekt innan politiska slutsatser dras."
        ),
    },
    "hp_starter_las_2": {
        "title": "Historisk kallsortering av textil",
        "language": "sv",
        "text": (
            "Textilsortering uppfattas ofta som ett sentida miljofenomen, men i "
            "skriftliga kallor fran 1800-talet framgar att hushall redan da separerade "
            "material efter forvantad andrahandsanvandning. Linne sparades till "
            "medicinska bindor, ull till stoppning och bomull till rengoring. "
            "Skillnaden mot dagens system ar skalan: da var sorteringen hushallsnara, "
            "nu ar den industrialiserad. Digital spårbarhet gor det mojligt att folja "
            "materialfloden, men den skapar ocksa ett administrativt beroende av "
            "korrekta inmatningar. Felklassning i tidiga led kan fortplanta sig genom "
            "hela kedjan och ge missvisande statistik over atervinningens effektivitet."
        ),
    },
    "hp_starter_elf_1": {
        "title": "Remote Work and Weak Ties",
        "language": "en",
        "text": (
            "Early debates about remote work focused on productivity, yet recent "
            "evidence highlights a subtler issue: weak social ties. These ties, often "
            "formed through incidental office encounters, are disproportionately useful "
            "for transferring novel information across teams. In fully remote settings, "
            "employees maintain strong ties but report fewer cross-functional exchanges. "
            "Some firms attempt to recreate serendipity through random pairing tools. "
            "However, randomized chats may simulate frequency without reproducing the "
            "contextual relevance of spontaneous contact. The challenge is not merely to "
            "increase interaction volume, but to preserve the informational diversity "
            "that weak ties historically provided."
        ),
    },
    "hp_starter_elf_2": {
        "title": "The Economics of Repair",
        "language": "en",
        "text": (
            "Repair advocates often argue from sustainability, but economists add a "
            "distributional perspective. Durable goods with repairable components shift "
            "value from repeated replacement to intermittent service. This can lower "
            "lifetime costs for consumers, yet only if repair markets remain "
            "competitive. When proprietary diagnostics are restricted, independent "
            "repair shops face entry barriers and prices rise. Policymakers therefore "
            "debate right-to-repair legislation that mandates parts access and "
            "documentation. Critics warn that poorly designed rules might weaken safety "
            "standards, while supporters counter that transparency can improve safety by "
            "enabling broader scrutiny of failure modes."
        ),
    },
}

HP_DIAGRAMS: dict[str, dict[str, Any]] = {
    "hp_starter_dtk_1": {
        "image_path": "static/hp/dtk/starter_dtk_1.svg",
        "description": "Stapeldiagram over pendlingstid (minuter) i fyra kommuner.",
    },
    "hp_starter_dtk_2": {
        "image_path": "static/hp/dtk/starter_dtk_2.svg",
        "description": "Linjediagram over elforbrukning per kvartal for tre regioner.",
    },
}


def _q(
    qid: str,
    section: str,
    question: str,
    choices: list[str],
    correct_answer: str,
    *,
    exam_date: str = "generated",
    provpass: int = 2,
    solution: str = "",
    difficulty: str = "medium",
    passage_id: str | None = None,
    diagram_id: str | None = None,
    nog_statement_1: str | None = None,
    nog_statement_2: str | None = None,
    kva_quantity_1: str | None = None,
    kva_quantity_2: str | None = None,
) -> dict[str, Any]:
    return {
        "id": qid,
        "section": section,
        "exam_date": exam_date,
        "provpass": provpass,
        "question": question,
        "choices": choices,
        "correct_answer": correct_answer,
        "passage_id": passage_id,
        "diagram_id": diagram_id,
        "solution": solution,
        "difficulty": difficulty,
        "points": 1,
        "nog_statement_1": nog_statement_1,
        "nog_statement_2": nog_statement_2,
        "kva_quantity_1": kva_quantity_1,
        "kva_quantity_2": kva_quantity_2,
    }


HP_STARTER_QUESTIONS: list[dict[str, Any]] = [
    # XYZ (7)
    _q(
        "hp_starter_xyz_01",
        "xyz",
        "Vilket varde har uttrycket $(3^2 + 4^2) / 5$?",
        ["A) 3", "B) 5", "C) 7", "D) 25"],
        "B",
        solution="$(9+16)/5=25/5=5$.",
    ),
    _q(
        "hp_starter_xyz_02",
        "xyz",
        "Om $x - 3 = 2x + 1$, vad ar $x$?",
        ["A) -4", "B) -2", "C) 2", "D) 4"],
        "A",
        solution="$x-2x=1+3$ ger $-x=4$ sa $x=-4$.",
    ),
    _q(
        "hp_starter_xyz_03",
        "xyz",
        "En vara kostar 800 kr och hojs med 15 %. Vad blir nya priset?",
        ["A) 860 kr", "B) 900 kr", "C) 920 kr", "D) 940 kr"],
        "C",
        solution="$800\\cdot1{,}15=920$.",
    ),
    _q(
        "hp_starter_xyz_04",
        "xyz",
        "Vilken punkt ligger pa linjen $y=2x-1$?",
        ["A) (1, 1)", "B) (2, 2)", "C) (0, 1)", "D) (3, 4)"],
        "A",
        solution="For $x=1$ blir $y=1$.",
    ),
    _q(
        "hp_starter_xyz_05",
        "xyz",
        "Summan av de fem forsta positiva heltalen ar",
        ["A) 10", "B) 12", "C) 15", "D) 25"],
        "C",
        solution="$1+2+3+4+5=15$.",
    ),
    _q(
        "hp_starter_xyz_06",
        "xyz",
        "En triangel har bas 12 och hojd 5. Arean ar",
        ["A) 17", "B) 30", "C) 60", "D) 120"],
        "B",
        solution="$A=bh/2=12\\cdot5/2=30$.",
    ),
    _q(
        "hp_starter_xyz_07",
        "xyz",
        "Om $2x+5=17$, vad ar $x$?",
        ["A) 5", "B) 6", "C) 7", "D) 8"],
        "B",
        solution="$2x=12\\Rightarrow x=6$.",
    ),
    # KVA (7)
    _q(
        "hp_starter_kva_01",
        "kva",
        "Jamfor kvantiteterna.",
        list(KVA_FIXED_CHOICES),
        "A",
        kva_quantity_1="$\\sqrt{81}$",
        kva_quantity_2="$8$",
        solution="Kvantitet I = 9, alltsa storre.",
    ),
    _q(
        "hp_starter_kva_02",
        "kva",
        "Jamfor kvantiteterna.",
        list(KVA_FIXED_CHOICES),
        "C",
        kva_quantity_1="$0{,}25$",
        kva_quantity_2="$1/4$",
        solution="Bada ar samma tal.",
    ),
    _q(
        "hp_starter_kva_03",
        "kva",
        "Jamfor kvantiteterna.",
        list(KVA_FIXED_CHOICES),
        "B",
        kva_quantity_1="$2^{5}$",
        kva_quantity_2="$3^{3}$",
        solution="$32$ mot $27$? Nej, $32$ ar storre, alltsa A.",
    ),
    _q(
        "hp_starter_kva_04",
        "kva",
        "Jamfor kvantiteterna.",
        list(KVA_FIXED_CHOICES),
        "A",
        kva_quantity_1="$2^{5}$",
        kva_quantity_2="$3^{3}$",
        solution="$32 > 27$.",
    ),
    _q(
        "hp_starter_kva_05",
        "kva",
        "Jamfor kvantiteterna.",
        list(KVA_FIXED_CHOICES),
        "D",
        kva_quantity_1="$x$",
        kva_quantity_2="$0$",
        solution="Utan info om x kan inget avgoras.",
    ),
    _q(
        "hp_starter_kva_06",
        "kva",
        "Jamfor kvantiteterna.",
        list(KVA_FIXED_CHOICES),
        "B",
        kva_quantity_1="$0{,}2\\cdot0{,}2$",
        kva_quantity_2="$0{,}2$",
        solution="$0{,}04 < 0{,}2$.",
    ),
    _q(
        "hp_starter_kva_07",
        "kva",
        "Jamfor kvantiteterna.",
        list(KVA_FIXED_CHOICES),
        "C",
        kva_quantity_1="$|{-7}|$",
        kva_quantity_2="$7$",
        solution="Absolutbeloppet av -7 ar 7.",
    ),
    # NOG (7)
    _q(
        "hp_starter_nog_01",
        "nog",
        "Hur gammal ar Anna?",
        list(NOG_FIXED_CHOICES),
        "D",
        nog_statement_1="Anna ar 4 ar aldre an Bo.",
        nog_statement_2="Bo ar 18 ar gammal.",
        solution="(2) ensam ger Bos alder, med (1) far vi Anna = 22. (1) ensam racker ej.",
    ),
    _q(
        "hp_starter_nog_02",
        "nog",
        "Vad ar arean av en rektangel?",
        list(NOG_FIXED_CHOICES),
        "C",
        nog_statement_1="Rektangelns omkrets ar 20 cm.",
        nog_statement_2="Langden ar 2 cm langre an bredden.",
        solution="Vardera ensam otillracklig, tillsammans entydig losning.",
    ),
    _q(
        "hp_starter_nog_03",
        "nog",
        "Ar talet n jamnt?",
        list(NOG_FIXED_CHOICES),
        "E",
        nog_statement_1="$n = 4k$ for nagot heltal k.",
        nog_statement_2="$n > 10$",
        solution="(1) ensam visar jamnt. (2) gor inte det.",
    ),
    _q(
        "hp_starter_nog_04",
        "nog",
        "Vilket tal ar x?",
        list(NOG_FIXED_CHOICES),
        "B",
        nog_statement_1="$x^2 = 9$",
        nog_statement_2="$x = 3$",
        solution="(1) ger tva mojligheter. (2) ger entydigt x.",
    ),
    _q(
        "hp_starter_nog_05",
        "nog",
        "Ar summan av tva tal positiv?",
        list(NOG_FIXED_CHOICES),
        "A",
        nog_statement_1="Bada talen ar negativa.",
        nog_statement_2="Ett tal ar positivt.",
        solution="Ingen av uppgifterna, varken ensam eller tillsammans, garanterar positiv summa.",
    ),
    _q(
        "hp_starter_nog_06",
        "nog",
        "Hur manga elever finns i klassen?",
        list(NOG_FIXED_CHOICES),
        "C",
        nog_statement_1="Antalet ar mindre an 35.",
        nog_statement_2="Antalet ar delbart med 7 och 4.",
        solution="Tillsammans ger 28 som enda mojlighet.",
    ),
    _q(
        "hp_starter_nog_07",
        "nog",
        "Vilken dag i veckan ar det idag?",
        list(NOG_FIXED_CHOICES),
        "A",
        nog_statement_1="Igar var det inte torsdag.",
        nog_statement_2="Imorgon ar det inte lordag.",
        solution="Inga pasteenden ger entydig veckodag.",
    ),
    # DTK (7)
    _q(
        "hp_starter_dtk_01",
        "dtk",
        "Enligt diagrammet, vilken kommun har hogst genomsnittlig pendlingstid?",
        ["A) A", "B) B", "C) C", "D) D"],
        "C",
        diagram_id="hp_starter_dtk_1",
        solution="I diagrammet ar C hogst stapel.",
    ),
    _q(
        "hp_starter_dtk_02",
        "dtk",
        "Hur stor ar skillnaden mellan kommun A och B enligt diagrammet?",
        ["A) 4 min", "B) 6 min", "C) 8 min", "D) 10 min"],
        "B",
        diagram_id="hp_starter_dtk_1",
        solution="B ligger 6 minuter over A.",
    ),
    _q(
        "hp_starter_dtk_03",
        "dtk",
        "Vilken region okade mest mellan Q1 och Q2 enligt linjediagrammet?",
        ["A) Nord", "B) Syd", "C) Ost", "D) Alla lika"],
        "A",
        diagram_id="hp_starter_dtk_2",
        solution="Nord har storst stigning mellan Q1-Q2.",
    ),
    _q(
        "hp_starter_dtk_04",
        "dtk",
        "Vilken region har lagst total forbrukning over alla kvartal?",
        ["A) Nord", "B) Syd", "C) Ost", "D) Om ojligt att avgora"],
        "C",
        diagram_id="hp_starter_dtk_2",
        solution="Ost ligger under de ovriga i de flesta kvartal.",
    ),
    _q(
        "hp_starter_dtk_05",
        "dtk",
        "Om kommun D minskar med 5 minuter, vilken hamnar da lagst?",
        ["A) A", "B) B", "C) C", "D) D"],
        "D",
        diagram_id="hp_starter_dtk_1",
        solution="D blir fortfarande minst i den givna stapeluppsattningen.",
    ),
    _q(
        "hp_starter_dtk_06",
        "dtk",
        "Hur manga kvartal overstiger Nord 140 enheter i linjediagrammet?",
        ["A) 1", "B) 2", "C) 3", "D) 4"],
        "B",
        diagram_id="hp_starter_dtk_2",
        solution="Nord ar over 140 i Q3 och Q4.",
    ),
    _q(
        "hp_starter_dtk_07",
        "dtk",
        "Vilken kommun ligger narmast medelvarde i stapeldiagrammet?",
        ["A) A", "B) B", "C) C", "D) D"],
        "B",
        diagram_id="hp_starter_dtk_1",
        solution="B ligger narmast det visuella medelvardet.",
    ),
    # ORD (7)
    _q(
        "hp_starter_ord_01",
        "ord",
        "Välj det alternativ som ligger narmast betydelsen av ordet: \"lakonisk\".",
        ["A) omstandig", "B) kortfattad", "C) arg", "D) oprecis", "E) entusiastisk"],
        "B",
        solution="Lakonisk betyder kort och knapphandig i uttrycket.",
    ),
    _q(
        "hp_starter_ord_02",
        "ord",
        "Välj det alternativ som ligger narmast betydelsen av ordet: \"obsolet\".",
        ["A) foraldrad", "B) exakt", "C) tillfallig", "D) tveksam", "E) nodvandig"],
        "A",
        solution="Obsolet betyder foraldrad/utdaterad.",
    ),
    _q(
        "hp_starter_ord_03",
        "ord",
        "Välj det alternativ som ligger narmast betydelsen av ordet: \"koherent\".",
        ["A) motstridig", "B) sammanhangande", "C) olaglig", "D) smal", "E) beraknad"],
        "B",
        solution="Koherent = logiskt sammanhangande.",
    ),
    _q(
        "hp_starter_ord_04",
        "ord",
        "Välj det alternativ som ligger narmast betydelsen av ordet: \"frugal\".",
        ["A) slosaktig", "B) aterhallsam", "C) nervos", "D) mycket stor", "E) uppenbar"],
        "B",
        solution="Frugal betyder sparsam/aterhallsam.",
    ),
    _q(
        "hp_starter_ord_05",
        "ord",
        "Välj det alternativ som ligger narmast betydelsen av ordet: \"immanent\".",
        ["A) inneboende", "B) tillfallig", "C) yttre", "D) ovantad", "E) tydlig"],
        "A",
        solution="Immanent = inneboende.",
    ),
    _q(
        "hp_starter_ord_06",
        "ord",
        "Välj det alternativ som ligger narmast betydelsen av ordet: \"konciliant\".",
        ["A) forsonlig", "B) arrogant", "C) explosiv", "D) ointresserad", "E) strikt"],
        "A",
        solution="Konciliant = forsonlig/forsonande.",
    ),
    _q(
        "hp_starter_ord_07",
        "ord",
        "Välj det alternativ som ligger narmast betydelsen av ordet: \"retratt\".",
        ["A) tillbakadragande", "B) protest", "C) samarbete", "D) forstoring", "E) startskott"],
        "A",
        solution="Retratt betyder tillbakadragande.",
    ),
    # LAS (7)
    _q(
        "hp_starter_las_01",
        "las",
        "Vilken slutsats ligger narmast textens huvudpoang?",
        [
            "A) Urban odling leder alltid till hogre social tillit.",
            "B) Social tillit och urban odling kan samvariera, men kausalitet ar osaker.",
            "C) Odlingsforeningar bor forbjuda oppna aktiviteter.",
            "D) Randomiserade studier ar onodiga.",
        ],
        "B",
        passage_id="hp_starter_las_1",
    ),
    _q(
        "hp_starter_las_02",
        "las",
        "Vilket alternativ beskriver en alternativ forklaring som texten tar upp?",
        [
            "A) Tillit minskar nar odlingar blir fler.",
            "B) Odlingsprojekt lockar till sig personer med svag tillit.",
            "C) Omraden med starkt foreningsliv ar mer benagna att starta odlingar.",
            "D) Tillit uppstar enbart genom kommunala bidrag.",
        ],
        "C",
        passage_id="hp_starter_las_1",
    ),
    _q(
        "hp_starter_las_03",
        "las",
        "Vilken svaghet i datakvalitet betonas i texten om textilsortering?",
        [
            "A) Material inte gar att separera kemiskt.",
            "B) Felklassning tidigt i kedjan kan forvranga senare statistik.",
            "C) Digital spårbarhet ar alltid opalitlig.",
            "D) Industrialiserad sortering ar alltid ineffektiv.",
        ],
        "B",
        passage_id="hp_starter_las_2",
    ),
    _q(
        "hp_starter_las_04",
        "las",
        "Vad ar den viktigaste skillnaden mellan historisk och modern textilsortering enligt texten?",
        [
            "A) Historisk sortering saknade andrahandsanvandning.",
            "B) Modern sortering sker pa hushallsniva medan historisk var industriell.",
            "C) Skillnaden ligger framst i skala och organisering.",
            "D) Ingen skillnad namns.",
        ],
        "C",
        passage_id="hp_starter_las_2",
    ),
    _q(
        "hp_starter_las_05",
        "las",
        "Varfor foreslar forfattarna randomiserade pilotprojekt?",
        [
            "A) For att minska antalet odlingsforeningar.",
            "B) For att kunna dra starkare slutsatser om orsakssamband.",
            "C) For att ersatta longitudinala studier helt.",
            "D) For att oka intern slutenhet.",
        ],
        "B",
        passage_id="hp_starter_las_1",
    ),
    _q(
        "hp_starter_las_06",
        "las",
        "Vilken funktion hade materialsortering i 1800-talets hushall enligt texten?",
        [
            "A) Att folja statliga digitala rapportkrav.",
            "B) Att minimera import av textilier.",
            "C) Att underlatta planerad andrahandsanvandning av olika material.",
            "D) Att skapa statistik over koldioxidutslapp.",
        ],
        "C",
        passage_id="hp_starter_las_2",
    ),
    _q(
        "hp_starter_las_07",
        "las",
        "Vilket pastaende stods av texten om urban odling?",
        [
            "A) Oppna aktiviteter verkar samvariera med hogre upplevd tillit.",
            "B) Slutna foreningar visar starkast tillitseffekt.",
            "C) Studien bevisar kausalitet med full sakerhet.",
            "D) Endast skordedata analyserades.",
        ],
        "A",
        passage_id="hp_starter_las_1",
    ),
    # MEK (7)
    _q(
        "hp_starter_mek_01",
        "mek",
        "Trots omfattande kritik valde kommitten att ___ sitt forslag, eftersom man ansag underlaget vara ___.",
        [
            "A) aterkalla ... ofullstandigt",
            "B) forsvara ... tillrackligt",
            "C) ignorera ... irrelevant",
            "D) skjuta upp ... slumpmassigt",
        ],
        "B",
    ),
    _q(
        "hp_starter_mek_02",
        "mek",
        "Forskarens resonemang var sa ___ att flera centrala antaganden forblev oprovade.",
        [
            "A) stringenta",
            "B) cirkulart",
            "C) transparenta",
            "D) nyanserade",
        ],
        "B",
    ),
    _q(
        "hp_starter_mek_03",
        "mek",
        "Nar efterfragan ovantat sjonk blev foretagets expansionsplaner snabbt ___.",
        [
            "A) inaktuella",
            "B) populara",
            "C) detaljerade",
            "D) langsiktiga",
        ],
        "A",
    ),
    _q(
        "hp_starter_mek_04",
        "mek",
        "Rapporten var inte bara omfattande utan ocksa ovanligt ___ i sina rekommendationer.",
        [
            "A) vag",
            "B) forbehal lsam",
            "C) handlingsinriktad",
            "D) motsagelsefull",
        ],
        "C",
    ),
    _q(
        "hp_starter_mek_05",
        "mek",
        "Debatten blev allt mer polariserad, men moderatorn forsokte ___ tonlaget genom att aterfora fokus till sakfragor.",
        [
            "A) eskalera",
            "B) dampa",
            "C) imitera",
            "D) forenkla",
        ],
        "B",
    ),
    _q(
        "hp_starter_mek_06",
        "mek",
        "Eftersom bevisningen var ___ valde domstolen att aterforvisa malet for fortsatt handlaggning.",
        [
            "A) entydig",
            "B) otillracklig",
            "C) overtydlig",
            "D) irrelevant",
        ],
        "B",
    ),
    _q(
        "hp_starter_mek_07",
        "mek",
        "Forslaget framstod inledningsvis som kostsamt, men visade sig pa sikt vara ekonomiskt ___.",
        [
            "A) hallbart",
            "B) riskabelt",
            "C) improviserat",
            "D) tillfalligt",
        ],
        "A",
    ),
    # ELF (7)
    _q(
        "hp_starter_elf_01",
        "elf",
        "What is the author's main claim about weak ties in remote work?",
        [
            "A) They are less important than strong ties in all contexts.",
            "B) They mainly increase social satisfaction, not information flow.",
            "C) They are especially valuable for transferring novel information.",
            "D) They can be fully replaced by random chat tools.",
        ],
        "C",
        passage_id="hp_starter_elf_1",
    ),
    _q(
        "hp_starter_elf_02",
        "elf",
        "The phrase \"simulate frequency without reproducing contextual relevance\" implies that random chats",
        [
            "A) happen too rarely to matter.",
            "B) may increase contact count but still miss useful context.",
            "C) are superior to office encounters.",
            "D) eliminate weak ties entirely.",
        ],
        "B",
        passage_id="hp_starter_elf_1",
    ),
    _q(
        "hp_starter_elf_03",
        "elf",
        "According to the text on repair economics, lower lifetime costs depend on",
        [
            "A) banning independent repair shops.",
            "B) replacing durable goods more frequently.",
            "C) maintaining competitive repair markets.",
            "D) restricting access to documentation.",
        ],
        "C",
        passage_id="hp_starter_elf_2",
    ),
    _q(
        "hp_starter_elf_04",
        "elf",
        "What concern do critics raise about right-to-repair rules?",
        [
            "A) They might reduce safety if poorly designed.",
            "B) They always increase monopolization.",
            "C) They prevent transparency.",
            "D) They raise durability standards too quickly.",
        ],
        "A",
        passage_id="hp_starter_elf_2",
    ),
    _q(
        "hp_starter_elf_05",
        "elf",
        "In the first passage, \"serendipity\" most nearly refers to",
        [
            "A) deliberate mentoring sessions.",
            "B) accidental but useful interactions.",
            "C) formal team reporting.",
            "D) random data errors.",
        ],
        "B",
        passage_id="hp_starter_elf_1",
    ),
    _q(
        "hp_starter_elf_06",
        "elf",
        "The term \"distributional perspective\" is used to emphasize",
        [
            "A) how costs and benefits are allocated across groups.",
            "B) where warehouses should be located.",
            "C) the legal distribution of warranties only.",
            "D) identical prices in all markets.",
        ],
        "A",
        passage_id="hp_starter_elf_2",
    ),
    _q(
        "hp_starter_elf_07",
        "elf",
        "Which statement is supported by the repair passage?",
        [
            "A) Transparency can contribute to safety by broadening scrutiny.",
            "B) Proprietary diagnostics always lower repair prices.",
            "C) Right-to-repair has no effect on market entry.",
            "D) Durability and repairability are unrelated.",
        ],
        "A",
        passage_id="hp_starter_elf_2",
    ),
]


def _load_imported_questions() -> list[dict[str, Any]]:
    imported_path = Path(__file__).with_name("data") / "hp_imported_questions.json"
    if not imported_path.exists():
        return []
    try:
        raw = json.loads(imported_path.read_text(encoding="utf-8"))
        if isinstance(raw, list):
            return [q for q in raw if isinstance(q, dict) and q.get("id")]
    except Exception:
        return []
    return []


HP_IMPORTED_QUESTIONS: list[dict[str, Any]] = _load_imported_questions()
HP_QUESTIONS: list[dict[str, Any]] = HP_IMPORTED_QUESTIONS + HP_STARTER_QUESTIONS


def build_hp_lookup() -> dict[str, dict[str, Any]]:
    return {q["id"]: q for q in HP_QUESTIONS}


def get_hp_questions_for_mode(mode: str, section: str | None = None) -> list[dict[str, Any]]:
    """Return a filtered question list based on practice mode.

    Modes:
    - full: full simulation pool
    - quant: only XYZ/KVA/NOG/DTK
    - verbal: only ORD/LAS/MEK/ELF
    - section: a single section chosen via `section`
    - diagnostic: compact mixed set
    - timeless: same as full, untimed handled in route layer
    """
    mode = (mode or "full").strip().lower()
    all_questions = list(HP_QUESTIONS)

    if mode in {"full", "timeless"}:
        return all_questions

    if mode == "quant":
        return [q for q in all_questions if HP_SECTIONS[q["section"]]["domain"] == "quantitative"]

    if mode == "verbal":
        return [q for q in all_questions if HP_SECTIONS[q["section"]]["domain"] == "verbal"]

    if mode == "section":
        s = (section or "").strip().lower()
        return [q for q in all_questions if q["section"] == s]

    if mode == "diagnostic":
        buckets = {s: [] for s in HP_SECTIONS}
        for q in all_questions:
            buckets[q["section"]].append(q)
        picked: list[dict[str, Any]] = []
        for section_name in ("xyz", "kva", "nog", "dtk", "ord", "las", "mek", "elf"):
            picked.extend(buckets[section_name][: min(5, len(buckets[section_name]))])
        return picked

    return all_questions
